# Generated by Django 5.0.6 on 2025-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cycle_length',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
